name: mvh
favicon: null
layout_spectrum: 0.96248
typography_spectrum: 0.7276083116885275
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f2f2f2'
    - '#ff81b5'
    - '#3991c7'
    - '#ff005b'
    - '#0a080a'
  brandStrength: 0
  lightness: 0.8125
  saturation: 0.25
  rhythmicContrast: 0.7364343027584255
purpose: []
