name: mvh
favicon: null
layout_spectrum: 0.49278
typography_spectrum: 0.7276083116885275
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbfbfb'
    - '#009cba'
    - '#686b74'
    - '#fc285e'
    - '#191215'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
