name: mvh
favicon: null
layout_spectrum: 1
typography_spectrum: 0.23886
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.5459448543842882
  lightness: 0.24148786533623934
  saturation: 0.8185255685821176
  rhythmicContrast: 0.7364343027584255
purpose: []
